### ISSUE TITLE
actor scraper stopped working

### ISSUE THREAD

**Issue by thierry400** [curtwagner1984/YAPO#35]
Hello,

I had no problems yesterday with scraping new actors.
Today after I updated Yapo I can't seem to scrape any actors.
(Problem is with both IMDB and freeones)

I also can't scrape actors I used to be able to scrape any more.
I always get something like this message: "freeOnesCould not find AJ ApplegateTry a different scraper or looking manually"

and the command promp gives me the following:

[28/Aug/2016 17:51:21] "GET /scrape-actor/?actor=68&force=true&scrapeSite=freeOnes HTTP/1.1" 500 78412
You are now in the scrape actor API REST view
Actor to scrape is: AJ Applegate
Site to scrape is: freeOnes
Internal Server Error: /scrape-actor/
Traceback (most recent call last):
  File "c:\py3virtualenv\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\py3virtualenv\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\py3virtualenv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\py3virtualenv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\py3virtualenv\lib\site-packages\rest_framework\views.py", line 468, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "c:\py3virtualenv\lib\site-packages\rest_framework\views.py", line 396, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[28/Aug/2016 17:51:37] "GET /scrape-actor/?actor=68&force=true&scrapeSite=freeOnes HTTP/1.1" 500 78411


Has any code on the scrapers been changed?

**Comment by sjclayton** [comment]
Yes, sorry - that was my mistake... I fudged something while I was cleaning some things up... it's fixed in the latest commit though.... if you re-pull it'll be all good.

**Comment by thierry400** [comment]
Indeed, after a re-pull I can scrape again
