### ISSUE TITLE
can't start server after latest pull 

### ISSUE THREAD

**Issue by thierry400** [curtwagner1984/YAPO#45]
Hello,

The last pull seems to have broken my YAPO.
I get the following in the command prompt: 

```

(py3virtualenv) C:\Yapo\YAPO>python manage.py runserver 0.0.0.0:8001
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
Performing system checks...

C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
Last full scene tagging : 2016-08-23 22:17:36
Actor Emma Stoned thumb path is: media/actor/3/profile/profile.jpg
 and it should be media/actor/3/profile/profile.jpg
False
Actor Kiera Winters thumb path is: media/actor/6/profile/profile.jpg
 and it should be media/actor/6/profile/profile.jpg
False
Actor Aische Pervers thumb path is: media/actor/8/profile/profile.jpg
 and it should be media/actor/8/profile/profile.jpg
False
Actor Desert Angel thumb path is: media/actor/11/profile/profile.jpg
 and it should be media/actor/11/profile/profile.jpg
False
Actor Dolly Little thumb path is: media/actor/12/profile/profile.jpg
 and it should be media/actor/12/profile/profile.jpg
False
Actor Emily 18 thumb path is: media/actor/13/profile/profile.jpg
 and it should be media/actor/13/profile/profile.jpg
False
Actor Hollie Mack thumb path is: media/actor/14/profile/profile.jpg
 and it should be media/actor/14/profile/profile.jpg
False
Actor Kaylee Haze thumb path is: media/actor/15/profile/profile.jpg
 and it should be media/actor/15/profile/profile.jpg
False
Actor Kimmy Teen thumb path is: media/actor/16/profile/profile.jpg
 and it should be media/actor/16/profile/profile.jpg
False
Actor Laura Shirley thumb path is: media/actor/17/profile/profile.jpg
 and it should be media/actor/17/profile/profile.jpg
False
Actor Lily Rader thumb path is: media/actor/18/profile/profile.jpg
 and it should be media/actor/18/profile/profile.jpg
False
Actor Melissa May thumb path is: media/actor/19/profile/profile.jpg
 and it should be media/actor/19/profile/profile.jpg
False
Actor Natalie Monroe thumb path is: media/actor/20/profile/profile.jpg
 and it should be media/actor/20/profile/profile.jpg
False
Actor Roxy Raye thumb path is: media/actor/22/profile/profile.jpg
 and it should be media/actor/22/profile/profile.jpg
False
Actor Sammie Daniels thumb path is: media/actor/23/profile/profile.jpg
 and it should be media/actor/23/profile/profile.jpg
False
Actor Sierra Nevadah thumb path is: media/actor/24/profile/profile.jpg
 and it should be media/actor/24/profile/profile.jpg
False
Actor Skye West thumb path is: media/actor/25/profile/profile.jpg
 and it should be media/actor/25/profile/profile.jpg
False
Actor Tali Dova thumb path is: media/actor/26/profile/profile.jpg
 and it should be media/actor/26/profile/profile.jpg
False
Actor Trisha Parks thumb path is: media/actor/27/profile/profile.jpg
 and it should be media/actor/27/profile/profile.jpg
False
Actor Alice Green thumb path is: media/actor/28/profile/profile.jpg
 and it should be media/actor/28/profile/profile.jpg
False
Actor Alex Tanner thumb path is: media/actor/29/profile/profile.jpg
 and it should be media/actor/29/profile/profile.jpg
False
Actor Stella Ann thumb path is: media/actor/30/profile/profile.jpg
 and it should be media/actor/30/profile/profile.jpg
False
Actor Heather Night thumb path is: media/actor/31/profile/profile.jpg
 and it should be media/actor/31/profile/profile.jpg
False
Actor Amber Cox thumb path is: media/actor/32/profile/profile.jpg
 and it should be media/actor/32/profile/profile.jpg
False
Actor Avril Hall thumb path is: media/actor/33/profile/profile.jpg
 and it should be media/actor/33/profile/profile.jpg
False
Actor Alexis Monroe thumb path is: media/actor/34/profile/profile.jpg
 and it should be media/actor/34/profile/profile.jpg
False
Actor Kagney Lynn Karter thumb path is: media/actor/35/profile/profile.jpg
 and it should be media/actor/35/profile/profile.jpg
False
Actor Nicky Angel thumb path is: media/actor/36/profile/profile.jpg
 and it should be media/actor/36/profile/profile.jpg
False
Actor Jamie Applegate thumb path is: media/actor/37/profile/profile.jpg
 and it should be media/actor/37/profile/profile.jpg
False
Actor Lily Love thumb path is: media/actor/38/profile/profile.jpg
 and it should be media/actor/38/profile/profile.jpg
False
Actor Ella Milano thumb path is: media/actor/39/profile/profile.jpg
 and it should be media/actor/39/profile/profile.jpg
False
Actor Mia Malkova thumb path is: media/actor/40/profile/profile.jpg
 and it should be media/actor/40/profile/profile.jpg
False
Actor Casana Lei thumb path is: media/actor/41/profile/profile.jpg
 and it should be media/actor/41/profile/profile.jpg
False
Actor Sky Light thumb path is: media/actor/42/profile/profile.jpg
 and it should be media/actor/42/profile/profile.jpg
False
Actor Vanda Lust thumb path is: media/actor/43/profile/profile.jpg
 and it should be media/actor/43/profile/profile.jpg
False
Actor Riley Reid thumb path is: media/actor/44/profile/profile.jpg
 and it should be media/actor/44/profile/profile.jpg
False
Actor Roxanne Rae thumb path is: media/actor/45/profile/profile.jpg
 and it should be media/actor/45/profile/profile.jpg
False
Actor Zoey Kush thumb path is: media/actor/46/profile/profile.jpg
 and it should be media/actor/46/profile/profile.jpg
False
Actor Amia Miley thumb path is: media/actor/47/profile/profile.jpg
 and it should be media/actor/47/profile/profile.jpg
False
Actor Holly Michaels thumb path is: media/actor/48/profile/profile.jpg
 and it should be media/actor/48/profile/profile.jpg
False
Actor Whitney Westgate thumb path is: media/actor/49/profile/profile.jpg
 and it should be media/actor/49/profile/profile.jpg
False
Actor Kacey Jordan thumb path is: media/actor/50/profile/profile.jpg
 and it should be media/actor/50/profile/profile.jpg
False
Actor April Oneil thumb path is: media/actor/51/profile/profile.jpg
 and it should be media/actor/51/profile/profile.jpg
False
Actor Avril Sun thumb path is: media/actor/52/profile/profile.jpg
 and it should be media/actor/52/profile/profile.jpg
False
Actor Zoey Monroe thumb path is: media/actor/53/profile/profile.jpg
 and it should be media/actor/53/profile/profile.jpg
False
Actor Lilly Banks thumb path is: media/actor/54/profile/profile.jpg
 and it should be media/actor/54/profile/profile.jpg
False
Actor Lexi Bloom thumb path is: media/actor/55/profile/profile.jpg
 and it should be media/actor/55/profile/profile.jpg
False
Actor Sensi Pearl thumb path is: media/actor/56/profile/profile.jpg
 and it should be media/actor/56/profile/profile.jpg
False
Actor Tasha Reign thumb path is: media/actor/57/profile/profile.jpg
 and it should be media/actor/57/profile/profile.jpg
False
Actor Jesse Jordan thumb path is: media/actor/58/profile/profile.jpg
 and it should be media/actor/58/profile/profile.jpg
False
Actor Lexi Belle thumb path is: media/actor/59/profile/profile.jpg
 and it should be media/actor/59/profile/profile.jpg
False
Actor Jessie Rogers thumb path is: media/actor/60/profile/profile.jpg
 and it should be media/actor/60/profile/profile.jpg
False
Actor Kyleigh Ann thumb path is: media/actor/61/profile/profile.jpg
 and it should be media/actor/61/profile/profile.jpg
False
Actor Jennifer White thumb path is: media/actor/62/profile/profile.jpg
 and it should be media/actor/62/profile/profile.jpg
False
Actor Karina White thumb path is: media/actor/63/profile/profile.jpg
 and it should be media/actor/63/profile/profile.jpg
False
Actor Allie James thumb path is: media/actor/64/profile/profile.jpg
 and it should be media/actor/64/profile/profile.jpg
False
Actor Chloe Foster thumb path is: media/actor/65/profile/profile.jpg
 and it should be media/actor/65/profile/profile.jpg
False
Actor Faye Reagan thumb path is: media/actor/66/profile/profile.jpg
 and it should be media/actor/66/profile/profile.jpg
False
Actor Fuuka thumb path is: media/actor/67/profile/profile.jpg
 and it should be media/actor/67/profile/profile.jpg
False
Actor AJ Applegate thumb path is: media/actor/68/profile/profile.jpg
 and it should be media/actor/68/profile/profile.jpg
False
Actor Schnuggie91 thumb path is: media/actor/69/profile/profile.jpg
 and it should be media/actor/69/profile/profile.jpg
False
Actor Proxy Paige thumb path is: media/actor/70/profile/profile.jpg
 and it should be media/actor/70/profile/profile.jpg
False
Actor Kylie Quinn thumb path is: media/actor/71/profile/profile.jpg
 and it should be media/actor/71/profile/profile.jpg
False
Actor Jasmine Webb thumb path is: media/actor/72/profile/profile.jpg
 and it should be media/actor/72/profile/profile.jpg
False
Actor Gina Gerson thumb path is: media/actor/73/profile/profile.jpg
 and it should be media/actor/73/profile/profile.jpg
False
Actor Dani Daniels thumb path is: media/actor/74/profile/profile.jpg
 and it should be media/actor/74/profile/profile.jpg
False
Actor Holly Hanna thumb path is: media/actor/75/profile/profile.jpg
 and it should be media/actor/75/profile/profile.jpg
False
Actor Curious Cristine thumb path is: media/actor/76/profile/profile.jpg
 and it should be media/actor/76/profile/profile.jpg
False
Actor Remy Lacroix thumb path is: media/actor/77/profile/profile.jpg
 and it should be media/actor/77/profile/profile.jpg
False
Actor Scarlett Red thumb path is: media/actor/78/profile/profile.jpg
 and it should be media/actor/78/profile/profile.jpg
False
Actor Anastasia Brill thumb path is: media/actor/79/profile/profile.jpg
 and it should be media/actor/79/profile/profile.jpg
False
Actor Bree olson thumb path is: media/actor/80/profile/profile.jpg
 and it should be media/actor/80/profile/profile.jpg
False
Actor Nicoleta Emilie thumb path is: media/actor/81/profile/profile.jpg
 and it should be media/actor/81/profile/profile.jpg
False
Actor Amber Chase thumb path is: media/actor/82/profile/profile.jpg
 and it should be media/actor/82/profile/profile.jpg
False
Actor Henessy thumb path is: media/actor/83/profile/profile.jpg
 and it should be media/actor/83/profile/profile.jpg
False
Actor Kelsie S thumb path is: media/actor/84/profile/profile.jpg
 and it should be media/actor/84/profile/profile.jpg
False
Actor DeeDee Lynn thumb path is: media/actor/85/profile/profile.jpg
 and it should be media/actor/85/profile/profile.jpg
False
Actor Elizabeth Anne thumb path is: media/actor/87/profile/profile.jpg
 and it should be media/actor/87/profile/profile.jpg
False
Actor Cindy Carson thumb path is: media/actor/89/profile/profile.jpg
 and it should be media/actor/89/profile/profile.jpg
False
Actor Taryn Elizabeth thumb path is: media/actor/90/profile/profile.jpg
 and it should be media/actor/90/profile/profile.jpg
False
Actor Harper Kelly thumb path is: media/actor/91/profile/profile.jpg
 and it should be media/actor/91/profile/profile.jpg
False
Actor Sidra Sins thumb path is: media/actor/92/profile/profile.jpg
 and it should be media/actor/92/profile/profile.jpg
False
Actor Naveen Ora thumb path is: media/actor/93/profile/profile.jpg
 and it should be media/actor/93/profile/profile.jpg
False
Actor Gabriella Paltrova thumb path is: media/actor/94/profile/profile.jpg
 and it should be media/actor/94/profile/profile.jpg
False
Actor Chase Hart thumb path is: media/actor/95/profile/profile.jpg
 and it should be media/actor/95/profile/profile.jpg
False
Actor Summer Breeze thumb path is: media/actor/96/profile/profile.jpg
 and it should be media/actor/96/profile/profile.jpg
False
Actor Lilyan Red thumb path is: media/actor/97/profile/profile.jpg
 and it should be media/actor/97/profile/profile.jpg
False
Actor Teen Lesley thumb path is: media/actor/98/profile/profile.jpg
 and it should be media/actor/98/profile/profile.jpg
False
Actor Dakota Skye thumb path is: media/actor/99/profile/profile.jpg
 and it should be media/actor/99/profile/profile.jpg
False
Actor Lucy Cat thumb path is: media/actor/100/profile/profile.jpg
 and it should be media/actor/100/profile/profile.jpg
False
Actor Rikki Rumor thumb path is: media/actor/101/profile/profile.jpg
 and it should be media/actor/101/profile/profile.jpg
False
Actor MerryGinn thumb path is: media/actor/102/profile/profile.jpg
 and it should be media/actor/102/profile/profile.jpg
False
Actor Pamela Sanchez thumb path is: media/actor/103/profile/profile.jpg
 and it should be media/actor/103/profile/profile.jpg
False
Actor Ash Hollywood thumb path is: media/actor/104/profile/profile.jpg
 and it should be media/actor/104/profile/profile.jpg
False
Actor Aubrey Gold thumb path is: media/actor/105/profile/profile.jpg
 and it should be media/actor/105/profile/profile.jpg
False
Actor Hope Harper thumb path is: media/actor/106/profile/profile.jpg
 and it should be media/actor/106/profile/profile.jpg
False
Actor Alyssa Hart thumb path is: media/actor/107/profile/profile.jpg
 and it should be media/actor/107/profile/profile.jpg
False
Actor Helen Flingston thumb path is: media/actor/108/profile/profile.jpg
 and it should be media/actor/108/profile/profile.jpg
False
Actor Jorden Kennedy thumb path is: media/actor/109/profile/profile.jpg
 and it should be media/actor/109/profile/profile.jpg
False
Actor Sandra Martin thumb path is: media/actor/110/profile/profile.jpg
 and it should be media/actor/110/profile/profile.jpg
False
Actor Maria Ozawa thumb path is: media/actor/111/profile/profile.jpg
 and it should be media/actor/111/profile/profile.jpg
False
Actor Jayna Oso thumb path is: media/actor/112/profile/profile.jpg
 and it should be media/actor/112/profile/profile.jpg
False
Actor Chloe Adams thumb path is: media/actor/114/profile/profile.jpg
 and it should be media/actor/114/profile/profile.jpg
False
Actor ZoexRydher thumb path is: media/actor/115/profile/profile.jpg
 and it should be media/actor/115/profile/profile.jpg
False
Actor Ada Costa thumb path is: media/actor/116/profile/profile.jpg
 and it should be media/actor/116/profile/profile.jpg
False
Actor Stoya thumb path is: media/actor/117/profile/profile.jpg
 and it should be media/actor/117/profile/profile.jpg
False
Actor Marya Tight thumb path is: media/actor/119/profile/profile.jpg
 and it should be media/actor/119/profile/profile.jpg
False
Actor Sayaka Takahashi thumb path is: media/actor/120/profile/profile.jpg
 and it should be media/actor/120/profile/profile.jpg
False
Actor Milana Fox thumb path is: media/actor/121/profile/profile.jpg
 and it should be media/actor/121/profile/profile.jpg
False
Actor Marie Konishi thumb path is: media/actor/122/profile/profile.jpg
 and it should be media/actor/122/profile/profile.jpg
False
Actor Lara Brookes thumb path is: media/actor/123/profile/profile.jpg
 and it should be media/actor/123/profile/profile.jpg
False
Actor Callie Calypso thumb path is: media/actor/124/profile/profile.jpg
 and it should be media/actor/124/profile/profile.jpg
False
Actor Ariana Marie thumb path is: media/actor/125/profile/profile.jpg
 and it should be media/actor/125/profile/profile.jpg
False
Actor Alexa Grace thumb path is: media/actor/126/profile/profile.jpg
 and it should be media/actor/126/profile/profile.jpg
False
Actor Ella Woods thumb path is: media/actor/127/profile/profile.jpg
 and it should be media/actor/127/profile/profile.jpg
False
Actor Kitten XX thumb path is: media/images/actor/Unknown/profile/profile.jpg
 and it should be media/actor/128/profile/profile.jpg
True
Actor Ashlyn Rae thumb path is: media/actor/130/profile/profile.jpg
 and it should be media/actor/130/profile/profile.jpg
False
Actor Viktoria Sweet thumb path is: media/actor/131/profile/profile.jpg
 and it should be media/actor/131/profile/profile.jpg
False
Actor Tida thumb path is: media/actor/132/profile/profile.jpg
 and it should be media/actor/132/profile/profile.jpg
False
Actor Natalia Rossi thumb path is: media/actor/133/profile/profile.jpg
 and it should be media/actor/133/profile/profile.jpg
False
Actor Elizabeth Hawkenson thumb path is: media/actor/134/profile/profile.jpg
 and it should be media/actor/134/profile/profile.jpg
False
Actor Kimberly Brix thumb path is: media/actor/135/profile/profile.jpg
 and it should be media/actor/135/profile/profile.jpg
False
Actor Erika Kurisu thumb path is: media/actor/136/profile/profile.jpg
 and it should be media/actor/136/profile/profile.jpg
False
Actor Sadie Pop thumb path is: media/actor/137/profile/profile.jpg
 and it should be media/actor/137/profile/profile.jpg
False
Actor Little Caprice thumb path is: media/actor/138/profile/profile.jpg
 and it should be media/actor/138/profile/profile.jpg
False
Actor Sasha Grey thumb path is: media/actor/139/profile/profile.jpg
 and it should be media/actor/139/profile/profile.jpg
False
Actor Emily Addison thumb path is: media/actor/140/profile/profile.jpg
 and it should be media/actor/140/profile/profile.jpg
False
Actor Randy Moore thumb path is: media/actor/141/profile/profile.jpg
 and it should be media/actor/141/profile/profile.jpg
False
Actor Christina Carter thumb path is: media/actor/142/profile/profile.jpg
 and it should be media/actor/142/profile/profile.jpg
False
Actor Jayden Cole thumb path is: media/actor/143/profile/profile.jpg
 and it should be media/actor/143/profile/profile.jpg
False
Actor Tomomi Nomura thumb path is: media/actor/144/profile/profile.jpg
 and it should be media/actor/144/profile/profile.jpg
False
Actor Lexxxi Nicole thumb path is: media/actor/145/profile/profile.jpg
 and it should be media/actor/145/profile/profile.jpg
False
Actor Uta Kohaku thumb path is: media/actor/146/profile/profile.jpg
 and it should be media/actor/146/profile/profile.jpg
False
Actor Mika Futaba thumb path is: media/actor/147/profile/profile.jpg
 and it should be media/actor/147/profile/profile.jpg
False
Actor Lily Carter thumb path is: media/actor/148/profile/profile.jpg
 and it should be media/actor/148/profile/profile.jpg
False
Actor Anikka Albrite thumb path is: media/actor/149/profile/profile.jpg
 and it should be media/actor/149/profile/profile.jpg
False
Actor Angela Kiss thumb path is: media/actor/150/profile/profile.jpg
 and it should be media/actor/150/profile/profile.jpg
False
Actor Little Kim thumb path is: media/actor/151/profile/profile.jpg
 and it should be media/actor/151/profile/profile.jpg
False
Actor Kattie Gold thumb path is: media/actor/152/profile/profile.jpg
 and it should be media/actor/152/profile/profile.jpg
False
Actor Kayden Kross thumb path is: media/actor/153/profile/profile.jpg
 and it should be media/actor/153/profile/profile.jpg
False
Actor Kenzi Marie thumb path is: media/actor/154/profile/profile.jpg
 and it should be media/actor/154/profile/profile.jpg
False
Actor Angie Moon thumb path is: media/actor/155/profile/profile.jpg
 and it should be media/actor/155/profile/profile.jpg
False
Actor Molly Jane thumb path is: media/actor/156/profile/profile.jpg
 and it should be media/actor/156/profile/profile.jpg
False
Actor Emily Grey thumb path is: media/actor/157/profile/profile.jpg
 and it should be media/actor/157/profile/profile.jpg
False
Actor Erotic Goddess Christina thumb path is: media/actor/159/profile/profile.jpg
 and it should be media/actor/159/profile/profile.jpg
False
Actor A Little Kink thumb path is: media/actor/160/profile/profile.jpg
 and it should be media/actor/160/profile/profile.jpg
False
Actor Juliette March thumb path is: media/actor/162/profile/profile.jpg
 and it should be media/actor/162/profile/profile.jpg
False
Actor Dallas Black thumb path is: media/actor/163/profile/profile.jpg
 and it should be media/actor/163/profile/profile.jpg
False
Actor Elsa Jean thumb path is: media/actor/164/profile/profile.jpg
 and it should be media/actor/164/profile/profile.jpg
False
Actor Maci Winslett thumb path is: media/actor/165/profile/profile.jpg
 and it should be media/actor/165/profile/profile.jpg
False
Actor Britney Amber thumb path is: media/actor/166/profile/profile.jpg
 and it should be media/actor/166/profile/profile.jpg
False
Actor Bibixxx thumb path is: media/actor/167/profile/profile.jpg
 and it should be media/actor/167/profile/profile.jpg
False
Actor Ann Harlow thumb path is: media/images/actor/Unknown/profile/profile.jpg
 and it should be media/actor/168/profile/profile.jpg
True
Actor Daisy Summers thumb path is: media/actor/169/profile/profile.jpg
 and it should be media/actor/169/profile/profile.jpg
False
Actor Little Karolina thumb path is: media/images/actor/Unknown/profile/profile.jpg
 and it should be media/actor/170/profile/profile.jpg
True
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001931C3AB0D0>
Traceback (most recent call last):
  File "c:\py3virtualenv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\py3virtualenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: videos_actortag_scene_tags

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\py3virtualenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "c:\py3virtualenv\lib\site-packages\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "c:\py3virtualenv\lib\site-packages\django\core\management\base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "c:\py3virtualenv\lib\site-packages\django\core\checks\registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "c:\py3virtualenv\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "c:\py3virtualenv\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "c:\py3virtualenv\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\py3virtualenv\lib\site-packages\django\core\urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\py3virtualenv\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\py3virtualenv\lib\site-packages\django\core\urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "c:\py3virtualenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Yapo\YAPO\YAPO\urls.py", line 180, in <module>
    actorTag.scene_tags.add(scene_tag_to_add)
  File "c:\py3virtualenv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 843, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "c:\py3virtualenv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 988, in _add_items
    new_ids = new_ids - set(vals)
  File "c:\py3virtualenv\lib\site-packages\django\db\models\query.py", line 258, in __iter__
    self._fetch_all()
  File "c:\py3virtualenv\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "c:\py3virtualenv\lib\site-packages\django\db\models\query.py", line 158, in __iter__
    for row in compiler.results_iter():
  File "c:\py3virtualenv\lib\site-packages\django\db\models\sql\compiler.py", line 802, in results_iter
    results = self.execute_sql(MULTI)
  File "c:\py3virtualenv\lib\site-packages\django\db\models\sql\compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "c:\py3virtualenv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "c:\py3virtualenv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\py3virtualenv\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "c:\py3virtualenv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\py3virtualenv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\py3virtualenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: videos_actortag_scene_tags
```

Any ideas how I can get it working again?

**Comment by curtwagner1984** [comment]
@thierry400 Yes ... try the latest pull.

**Comment by thierry400** [comment]
It is fixed again thanks.
That was very quick!

**Comment by curtwagner1984** [comment]
@thierry400  Not really, I noticed @sjclayton message about it more than 2 hours ago, and was trying to fix it since.

**Comment by thierry400** [comment]
Hmm didn't notice that message.
Just coinidence then that i just pulled a few minutes before it got fixed.

Still thanks for all the effort and the good job :+1:

**Comment by thierry400** [comment]
I do seem to get another problem now.

Whenever i try to play a scene, my VLC player opens but i get this error in VLC:

Lezen van bestand mislukt:
VLC kon het bestand "Z:\Overige\Videos\[clips4sale.com]SKYLASFAMILYALBUMLARGE.wmv" niet openen (Bad file descriptor).
Uw invoer kan niet geopend worden:
VLC kon de MRL 'file:///Z:/Overige/Videos/%5Bclips4sale.com%5DSKYLASFAMILYALBUMLARGE.wmv' niet openen. Controleer het logboek voor details.

Translated this is something like:

Reading of file failed:
VLC could not open the file "Z:\Overige\Videos\[clips4sale.com]SKYLASFAMILYALBUMLARGE.wmv" (Bad file descriptor).
Your input can not be opened:
VLC could not open MRL 'file:///Z:/Overige/Videos/%5Bclips4sale.com%5DSKYLASFAMILYALBUMLARGE.wmv' Check the log for details.

YAPO command prompt gives no errors:
Play count for scene '[clips4sale.com]SKYLASFAMILYALBUMLARGE' is now '2' and the date the scene was last played is '2016-09-04 22:18:18.792445'
[04/Sep/2016 22:18:18] "GET /play-scene/?sceneId=4164 HTTP/1.1" 200 0


I don't realy know where the vlc log is located. I'l post that too if i find it.

**Comment by curtwagner1984** [comment]
@thierry400 I didn't change anything that relates to how vlc opens files. Did you check that the file is actually there ? If it is, did you try to open it with vlc manually ?

**Comment by thierry400** [comment]
I opened it manualy and that works just fine. I'll now try to reboot everything and see if that helps

**Comment by curtwagner1984** [comment]
@thierry400 can you try to open it using the command line ?

**Comment by thierry400** [comment]
It must have been something weird with my VLC or my computer.

Rebooting it has solved my problem
