### ISSUE TITLE
[Bug] YAPO loads blank

### ISSUE THREAD

**Issue by firewalkwithme93** [curtwagner1984/YAPO#46]
When I try to open up YAPO, the page is just blank. Here's my console from opening to now:

C:\py3virtualenv\Scripts>activate

(py3virtualenv) C:\py3virtualenv\Scripts>cd ..

(py3virtualenv) C:\py3virtualenv>cd ..

(py3virtualenv) C:\>cd yapo

(py3virtualenv) C:\Yapo>cd yapo

(py3virtualenv) C:\Yapo\YAPO>python manage.py runserver 127.0.0.1:8001
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
Performing system checks...

C:\Program Files\VideoLAN\VLC\vlc.exe
System check identified some issues:

WARNINGS:
videos.Actor.actor_aliases: (fields.W340) null has no effect on ManyToManyField.
videos.Actor.actor_tags: (fields.W340) null has no effect on ManyToManyField.
videos.ActorTag.scene_tags: (fields.W340) null has no effect on ManyToManyField.
videos.Folder.scenes: (fields.W340) null has no effect on ManyToManyField.
videos.Scene.actors: (fields.W340) null has no effect on ManyToManyField.
videos.Scene.scene_tags: (fields.W340) null has no effect on ManyToManyField.
videos.Scene.websites: (fields.W340) null has no effect on ManyToManyField.
videos.Website.scene_tags: (fields.W340) null has no effect on ManyToManyField.

System check identified 8 issues (0 silenced).
September 06, 2016 - 03:16:52
Django version 1.9.6, using settings 'YAPO.settings'
Starting development server at http://127.0.0.1:8001/
Quit the server with CTRL-BREAK.
[06/Sep/2016 03:16:55] "GET / HTTP/1.1" 200 9236
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/jquery/dist/jquery.min.js HTTP/1.1" 404 1757
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 1784
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 1790
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular/angular.js HTTP/1.1" 404 1736
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-animate/angular-animate.min.js HTTP/1.1" 404 1796
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-route/angular-route.min.js HTTP/1.1" 404 1784
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-xeditable/dist/css/xeditable.css HTTP/1.1" 404 1802
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-resource/angular-resource.min.js HTTP/1.1" 404 1802
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-img-cropper/dist/angular-img-cropper.min.js HTTP/1.1" 404 1835
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/ngstorage/ngStorage.js HTTP/1.1" 404 1748
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-xeditable/dist/js/xeditable.js HTTP/1.1" 404 1796
[06/Sep/2016 03:16:55] "GET /static/bower/bower_components/angular-xeditable/dist/css/xeditable.css HTTP/1.1" 404 1802
[06/Sep/2016 03:18:36] "GET / HTTP/1.1" 200 9236
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/jquery/dist/jquery.min.js HTTP/1.1" 404 1757
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 1784
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 1790
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular/angular.js HTTP/1.1" 404 1736
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-animate/angular-animate.min.js HTTP/1.1" 404 1796
[06/Sep/2016 03:18:36] "GET /static/js/dep-not-in-bower/ui-bootstrap-tpls-1.3.3.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/actor/actor.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-xeditable/dist/css/xeditable.css HTTP/1.1" 404 1802
[06/Sep/2016 03:18:36] "GET /static/js/app/core/scene/scene.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/actor/actor.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/actor-alias/actor-alias.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/scene/scene.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/actor-alias/actor-alias.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/actor-tag/actor-tag.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/scene-tag/scene-tag.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/actor-tag/acotr-tag.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/scene-tag/scene-tag.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/website/website.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/website/website.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-alias-list/actor-alias-list.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/db-folder/db-folder.service.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/db-folder/db-folder.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-alias-list/actor-alias-list.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/website-list/website-list.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/website-list/website-list.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/website-detail/website-detail.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-tag-list/scene-tag-list.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/website-detail/website-detail.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-tag-list/scene-tag-list.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-tag-detail/scene-tag-detail.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-tag-detail/scene-tag-detail.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-tag-list/actor-tag-list.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-tag-list/actor-tag-list.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-tag-detail/actor-tag-detail.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-tag-detail/actor-tag-detail.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-list/scene-list.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-detail/scene-detail.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-list/scene-list.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/scene-detail/scene-detail.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/db-folder-tree/db-folder-tree.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/db-folder-tree/db-folder-tree.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/detail-profile-image/detail-profile-image.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/detail-profile-image/detail-profile-image.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/pagination/pagination.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/pagination/pagination.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/async-typeahead/async-typeahead.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/async-typeahead/async-typeahead.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/section-list-wrapper/section-list-wrapper.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/nav-bar/nav-bar.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/nav-bar/nav-bar.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/section-list-wrapper/section-list-wrapper.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/add-items/add-items.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/add-items/add-items.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/settings/settings.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/settings/settings.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-list/actor-list.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-list/actor-list.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-detail/actor-detail.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/actor-detail/actor-detail.component.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/core.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/core/checkmark/checkmark.filter.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/app.module.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/app.upload.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/app.controller.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/app.config.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/js/app/app.services.js HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/css/angular/styles.css HTTP/1.1" 304 0
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-route/angular-route.min.js HTTP/1.1" 404 1784
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-resource/angular-resource.min.js HTTP/1.1" 404 1802
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-img-cropper/dist/angular-img-cropper.min.js HTTP/1.1" 404 1835
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-xeditable/dist/js/xeditable.js HTTP/1.1" 404 1796
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/ngstorage/ngStorage.js HTTP/1.1" 404 1748
[06/Sep/2016 03:18:36] "GET /static/bower/bower_components/angular-xeditable/dist/css/xeditable.css HTTP/1.1" 404 1802
[06/Sep/2016 03:18:37] "GET /static/favicon-16x16.png HTTP/1.1" 200 804

**Comment by curtwagner1984** [comment]
There are a bunch of 404s ... It can't find the static files. When was the last time it worked correctly and what have you changed since then ?

**Comment by firewalkwithme93** [comment]
Well, I loaded it up a few hours ago for the first time in a few days and my database was bizarrely completely empty. I decided to reinstall from the beginning, and it all went well except now I have this issue. So I suppose I fucked up somewhere along the way :p

**Comment by sjclayton** [comment]
@firewalkwithme93 Did you get it working...??

**Comment by curtwagner1984** [comment]
@firewalkwithme93 It seems you skipped the `bower install` step when reinstalling. Well you could simply do the steps to install the bower dependencies ... I don't remember the precise commands but as far as I do remember you need to go to `/static/bower` and type `bower install` better check in the readme for the exact instructions.

**Comment by firewalkwithme93** [comment]
I'm kind of confused, because I directed the virtualenv to C:\Yapo\YAPO\videos\static\bower and ran bower install, the folder now has bower_components and bower.json but it's still not launching properly. Now I get:

C:\Yapo\YAPO>python manage.py runserver 127.0.0.1:8001
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
Static files dir is: C:\Yapo\YAPO\videos\static
Media files dir is: C:\Yapo\YAPO\videos\media
Unhandled exception in thread started by <function wrapper at 0x03E526F0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Yapo\YAPO\videos\models.py", line 5, in <module>
    from mptt.models import MPTTModel, TreeForeignKey
  File "C:\Python27\lib\site-packages\mptt\models.py", line 385, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "C:\Python27\lib\site-packages\django\utils\six.py", line 808, in __new__
    return meta(name, bases, d)
  File "C:\Python27\lib\site-packages\mptt\models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Python27\lib\site-packages\mptt\managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute

**Comment by firewalkwithme93** [comment]
I started from the beginning again, not sure what I did different this time but it seems to be working fine again :dancer: thanks for the help as always!

**Comment by curtwagner1984** [comment]
@firewalkwithme93  Why it's looking in Python27? There should be Python3

**Comment by firewalkwithme93** [comment]
Yeah, I think maybe that's where things messed up - I already have a pre-existing Python installation of 27, and I had that as well as 35 running separately just fine, but perhaps I mixed them up when reinstalling

**Comment by curtwagner1984** [comment]
@firewalkwithme93 Using the correct virtualenv should take care of running the correct python versions. You can have as many versions of python as you want installed simultaneously .

**Comment by firewalkwithme93** [comment]
Okay, everything working smoothly - except for a strange error I've never had before. I was trying to import my scenes and this interrupted it:

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000014E36446D90>
Traceback (most recent call last):
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python35virtualenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "c:\python35virtualenv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check_migrations()
  File "c:\python35virtualenv\lib\site-packages\django\core\management\commands\runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "c:\python35virtualenv\lib\site-packages\django\db\migrations\executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "c:\python35virtualenv\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "c:\python35virtualenv\lib\site-packages\django\db\migrations\loader.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "c:\python35virtualenv\lib\site-packages\django\db\migrations\recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "c:\python35virtualenv\lib\site-packages\django\db\migrations\recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\base\introspection.py", line 58, in table_names
    return get_names(cursor)
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\base\introspection.py", line 53, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\sqlite3\introspection.py", line 68, in get_table_list
    ORDER BY name""")
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\python35virtualenv\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "c:\python35virtualenv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "c:\python35virtualenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: disk I/O error

**Comment by curtwagner1984** [comment]
@firewalkwithme93 I have never seen this error too. I don't think the problem is with Yapo...  It might have something to do with write permissions.

You did run `makemigrations` and `migrate` without a problem ?

**Comment by firewalkwithme93** [comment]
I did, but for some reason it didn't like it anyway. I deleted the database (since it didn't have anything in it, anyway) and ran `migrate` to make a new db and it seems to be going fine now.

**Comment by curtwagner1984** [comment]
@firewalkwithme93 Wait, so now it works?

**Comment by firewalkwithme93** [comment]
@curtwagner1984 Yep, it's been importing for a few minutes now and doesn't seem to have run into the disk I/O error again. Fingers crossed.

**Comment by curtwagner1984** [comment]
@firewalkwithme93 Strange... However it seems the problem is somewhere in your specific setup and not in Yapo.

**Comment by firewalkwithme93** [comment]
@curtwagner1984 Definitely seems to be the case, this is what happens when you try to use a computer when sick with the flu I think :+1:

**Comment by sjclayton** [comment]
@curtwagner1984 Can be closed now most likely..?
